os: linux
dist: xenial
language: python
matrix:
  include:
    - name: "Python 3.7 Xenial AMD64"
      python: 3.7
      dist: xenial
    - name: "Python 3.8 Xenial AMD64"
      python: 3.8
      dist: xenial

    - name: "Python 3.7 Xenial ARM64"
      python: 3.7
      arch: arm64
      dist: xenial
    - name: "Python 3.8 Xenial ARM64"
      python: 3.8
      arch: arm64
      dist: xenial
    - name: "Python 3.7 Xenial ARM64-GRAVITON2"
      python: 3.7
      arch: arm64-graviton2
      dist: xenial
      virt: lxd
      group: edge
    - name: "Python 3.8 Xenial ARM64-GRAVITON2"
      python: 3.8
      arch: arm64-graviton2
      dist: xenial
      virt: lxd
      group: edge
addons:
  apt:
    sources:
    - sourceline: 'ppa:sergey-dryabzhinsky/packages'

install:
- sudo apt-get update -qq
- sudo apt-get install -qq libzstd-dev

script:
- python setup.py test
- python setup.py clean -a
- env PYZSTD_LEGACY=1 python setup.py --pyzstd-legacy test
- python setup.py clean -a
- env LEGACY=1 PYZSTD_LEGACY=1 python setup.py --legacy --pyzstd-legacy test
- python setup.py clean -a
- python setup.py --external test
- python setup.py clean -a
